#!/bin/bash  -l
#SBATCH --job-name="matlab_BIGMACS"
#SBATCH --partition=largemem
#SBATCH --output=R58.log
#SBATCH --time=72:00:00
#SBATCH --mail-user=yuxin_zhou@ucsb.edu
#SBATCH --mail-type=ALL
#SBATCH --nodes=1 --ntasks-per-node 40
#SBATCH --mem=1200Gb
#  this is asking for 1 node, with 1 core (i.e. a Serial job)
#     the -l is needed on first line if you want to use modules

module load MatLab/R2021b

cd $SLURM_SUBMIT_DIR

/bin/hostname

matlab -nodisplay -nodesktop -nospxlash < main.m

