#!/bin/bash
#PBS -N matlab_pct
#PBS -A UCSB0015
#PBS -l walltime=8:00:00
#PBS -q casper
#PBS -j oe
#PBS -k eod
#PBS -o R56.log
#PBS -l select=1:ncpus=10:mpiprocs=10:mem=100GB
#PBS -m abe
#PBS -M yuxin_zhou@ucsb.edu

module load matlab

# # Derive the number of workers to use in the toolbox run script
# export NUMWORKERS=$(wc -l $PBS_NODEFILE | cut -d' ' -f1)

SECONDS=0
matlab -nodesktop -nosplash -r 'run main.m'
echo "Time elapsed = $SECONDS s"
